import entropy_weighted_coin
import entropy_geo_variable
import entropy_mutual_info_venn_diagram
import pointwise_rel_entropy_continuation
import relative_entropy_binomial_distributions
import noise_only_increases_entropy
import mnist_example
import uniform_distribution_maximises_entropy

entropy_weighted_coin.main()
entropy_geo_variable.main()
entropy_mutual_info_venn_diagram.main()
pointwise_rel_entropy_continuation.main()
relative_entropy_binomial_distributions.main()
noise_only_increases_entropy.main()
mnist_example.main()
uniform_distribution_maximises_entropy.main()
