import entropy_function_plot
import entropy_mutual_info_venn_diagram
import pointwise_rel_entropy_continuation
import relative_entropy_binomial_distributions

entropy_function_plot.main()
entropy_mutual_info_venn_diagram.main()
pointwise_rel_entropy_continuation.main()
relative_entropy_binomial_distributions.main()
